---
include:
- "**/*.rb"
exclude:
- spec/**/*
- lib/solargraph/rails/annotations/**/*
- vendor/**/*
- ".bundle/**/*"
require:
  # we generally assume a solargraph require has been made and don't make it explicitly
  - solargraph
domains: []
reporters: []
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
