include:
- "**/*.rb"
exclude:
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require:
  # assume we've included these in rails app before using them
  - date
  - time
  - json
  - turbo-rails
domains: []
reporters: []
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: [solargraph-rails]
max_files: 5000
