---
# To debug locally:
#   npm install -g act
#   act pull_release -j overcommit
#

name: Overcommit

on:
  workflow_dispatch: {}
  pull_request:
    branches: [main]
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  overcommit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          # ruby 3.2 is minimum Ruby supported by Rails 8.0
          - ruby: "3.2"
            rails-major: "8"
            rails-minor: "0"
            run_coverage: true
        solargraph-version:
          - "0.56.alpha"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        # Number of commits to fetch. 0 indicates all history for all branches and tags.
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler: latest
          bundler-cache: true
          cache-version: ${{ matrix.solargraph-version }}-${{ matrix.versions.rails-major }}.${{ matrix.versions.rails-minor }}-2025-06-06
        env:
          MATRIX_SOLARGRAPH_VERSION: ${{ matrix.solargraph-version }}
          MATRIX_RAILS_VERSION: ${{ matrix.versions.rails-major }}.${{ matrix.versions.rails-minor }}
          MATRIX_RAILS_MAJOR_VERSION: ${{ matrix.versions.rails-major }}

      - name: Restore cache of gem annotations
        id: dot-cache-restore
        uses: actions/cache/restore@v4
        with:
          key: |
            2025-06-26-09-${{ runner.os }}-dot-cache-${{ matrix.solargraph-version }}-${{ matrix.versions.rails-major }}--${{ matrix.versions.rails-minor }}-${{ hashFiles('spec/**/Gemfile.lock') }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            2025-06-26-09-${{ runner.os }}-dot-cache-${{ matrix.solargraph-version }}-${{ matrix.versions.rails-major }}-${{ matrix.versions.rails-minor }}-${{ hashFiles('spec/**/Gemfile.lock') }}-
            2025-06-26-09-${{ runner.os }}-dot-cache-${{ matrix.solargraph-version }}-${{ matrix.versions.rails-major }}-${{ matrix.versions.rails-minor }}-
            2025-06-26-09-${{ runner.os }}-dot-cache-${{ matrix.solargraph-version }}-${{ matrix.versions.rails-major }}-
            2025-06-26-09-${{ runner.os }}-dot-cache-${{ matrix.solargraph-version }}-
          path: |
            /home/runner/.cache/solargraph

      - name: Overcommit
        run: |
          bundle exec overcommit --sign
          bundle exec overcommit --run --diff origin/main
        env:
          MATRIX_SOLARGRAPH_VERSION: ${{ matrix.solargraph-version }}
          MATRIX_RAILS_VERSION: ${{ matrix.versions.rails-major }}.${{ matrix.versions.rails-minor }}
          MATRIX_RAILS_MAJOR_VERSION: ${{ matrix.versions.rails-major }}
